"""Process-local Squeekboard resource styles; no global GTK configuration edits."""
import os
from pathlib import Path
import re
import tomllib

STYLES = {"omarchy", "rounded", "contrast"}
DEFAULT_COLORS = {"background": "#242730", "foreground": "#e6e8ef", "accent": "#8ab4f8"}


def palette(path):
    try:
        colors = tomllib.loads(path.read_text())
    except (OSError, ValueError):
        colors = {}
    return {key: colors.get(key) if isinstance(colors.get(key), str) and
            re.fullmatch(r"#[0-9a-fA-F]{6}", colors[key]) else fallback
            for key, fallback in DEFAULT_COLORS.items()}


def luminance(color):
    channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4 for c in channels]
    return sum(c * w for c, w in zip(linear, (.2126, .7152, .0722)))


def stylesheet(colors, style):
    if style not in STYLES:
        raise ValueError("Unknown keyboard style")
    bg, fg, accent = (colors[k] for k in ("background", "foreground", "accent"))
    ink = "#000000" if luminance(accent) > .179 else "#ffffff"
    radius = {"omarchy": 4, "rounded": 12, "contrast": 4}[style]
    border = f"1px solid alpha({fg}, 0.16)"
    key = f"mix({bg}, {fg}, 0.08)"
    if style == "contrast":
        fg = "#000000" if luminance(bg) > .179 else "#ffffff"
        border = f"2px solid {fg}"
        key = bg
    return f'''@import url("resource:///sm/puri/squeekboard/common.css");
/* Generated by Omarchy Tablet. Scoped to Squeekboard only. */
sq_view {{ background: {bg}; color: {fg}; font-family: sans-serif; font-size: 1.5em; }}
sq_button {{
    color: {fg}; background: {key}; border: {border};
    border-radius: {radius}px; margin: 3px; box-shadow: none;
}}
sq_view.wide sq_button {{ margin: 4px; }}
sq_button.altline, sq_button.wide, sq_button.special, sq_button.change-view {{
    background: mix({bg}, {fg}, 0.16);
}}
sq_button.action {{ font-size: 0.75em; }}
sq_button.small {{ font-size: 0.5em; }}
sq_button.small-row {{ font-size: 0.575em; margin: 2px; border-width: 1px; }}
sq_button:active, sq_button.latched, sq_button.locked, sq_button#Return {{
    background: {accent}; color: {ink}; border-color: {accent};
}}
sq_button.latched, sq_button.locked {{ font-weight: bold; }}
sq_button#Return:active {{ background: mix({accent}, {ink}, 0.15); }}
'''


class KeyboardTheme:
    def __init__(self, runtime, theme_path=None):
        self.directory = runtime / "keyboard-style"
        state = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state"))
        self.theme_path = theme_path or state / "omarchy/current/theme/colors.toml"

    def prepare(self, style):
        css = stylesheet(palette(self.theme_path), style)
        self.directory.mkdir(parents=True, exist_ok=True)
        target = self.directory / "style.css"
        if not target.exists() or target.read_text() != css:
            tmp = target.with_suffix(".tmp")
            tmp.write_text(css)
            tmp.replace(target)
        return css

    def environment(self):
        # GTK_THEME forces Squeekboard's generic style resource. GLib overlays
        # replace that resource for this process without patching the package.
        return ["GTK_THEME=Adwaita", f"G_RESOURCE_OVERLAYS=/sm/puri/squeekboard={self.directory}"]
